### PR TITLE
Let's work on this :)

### PR DESCRIPTION
**Pull request by pythonleo**
i spent a while figuring out how 2 use a pull req so it took a while but now it's here so let's go

### CODE REVIEW

**Comment by The-UltimateGamer** [comment]
Merged!

**Comment by pythonleo** [comment]
okay

**Comment by pythonleo** [comment]
now i'm gonna go organize my mw's and stuff for tomorrow
so bye

**Comment by The-UltimateGamer** [comment]
bye
btw the template is real good




------------------&nbsp;Original&nbsp;------------------

**Pull request merged**
